/* autogenerated by Processing revision 1296 on 2026-01-15 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import processing.sound.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Empfaenger extends PApplet {




int res = 5;


public void settings(){
  size(120*res, 160*res);
}


public void setup(){
  
  background(255, 0, 0);
  noStroke();
  
  // Signal laden und analysieren
  s = new Signal("toneSignal.wav");
  
  // Bildpunkte zeichnen
  for (int i = 0; i < s.amplitudes.length; i++){
    fill(s.amplitudes[i] * 255);
    rect((i % 120) * res, floor(i / 120) * res, res, res);
  }
  
  //saveFrame("result.png");
}


public void draw(){}
Signal s;


class Signal{
  
  
  float[] amps;
  int sampleRate;
  
  float[] samples;
  float[] amplitudes;
  
  
  Signal(String fileName){
    
    // .wav-Datei auslesen
    byte[] bytes = loadBytes(fileName);
    int blockAlign = LEtoInt(bytes, 32, 2);

    samples = new float[(bytes.length - 44) / blockAlign];
    
    // Auslesen der Abtastwerte
    for (int i = 0; i < samples.length; i++){
      int val = LEtoInt(bytes, 44 + i * blockAlign, blockAlign);
      samples[i] = (float) val / pow(2, (8 * blockAlign) - 1);
    }
    
    // Frequenzen auslesen
    readFrequencies();
  }
  
  
  // Füllt das Frequenz-Array
  public void readFrequencies(){    
    
    amplitudes = new float[160 * 120];
    
    // Auslesen der Basis-Frequenz
    float baseValue = dft(1);
    
    // Skalieren der Amplituden-Werte
    for (int i = 2; i < 160 * 120 + 2; i++){
    
      // Der Farbwert wird als Prozentwert an der Basisfrequenz interpretiert.
      float val = dft(i);
      val /= baseValue;
      
      amplitudes[i - 2] = val;
    }
  }
  
  
  // Diskrete Fourier-Transformation
  public float dft(int xi){
    
    int N = samples.length;
    float[] avg = new float[] {0, 0};
    
    // Komplexe Summe bilden
    for (int n = 0; n < N; n++){
      avg[0] += samples[n] * cos(-xi * n * TAU / N); // Realteil
      avg[1] += samples[n] * sin(-xi * n * TAU / N); // Imaginärteil
    }
    
    return dist(0, 0, avg[0], avg[1]);
  }
}


// Konvertiere Little Endian Bytes in Integer
public int LEtoInt(byte[] bytes, int startByte, int blockLength){
  
  int result = 0;
  
  for (int i = blockLength - 1; i >= 0; i--){
    int val = bytes[startByte + i];
    if (i < blockLength - 1 && val < 0) val = 256 + val;
    val *= pow(2, i * 8);
    result += val;
  }
  
  return result;
}


  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "Empfaenger" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
