/* autogenerated by Processing revision 1296 on 2025-03-19 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import processing.sound.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Empfaenger extends PApplet {



Signal s;


public void setup(){
  
  /* size commented out by preprocessor */;
  background(255, 0, 0);
  noStroke();
  
  // Signal laden und analysieren
  s = new Signal("toneSignal.wav");
  
  // Bildpunkte zeichnen
  for (int i = 0; i < s.amplitudes.length; i++){
    fill(s.amplitudes[i] * 255);
    rect((i % 160) * 7, floor(i / 160) * 7, 7, 7);
  }
  
  saveFrame("result.png");
}


public void draw(){
}
float zoom = 50;


class Signal{
  
  float[] amps;
  int sampleRate;
  
  float[] samples;
  float[] amplitudes;
  
  
  Signal(String fileName){
    
    byte[] bytes = loadBytes(fileName);
    int blockAlign = LEtoInt(bytes, 32, 2);
    
    samples = new float[(bytes.length - 44) / blockAlign];
    
    // Auslesen der Abtastwerte
    for (int i = 0; i < samples.length; i++){
      int val = LEtoInt(bytes, 44 + i * blockAlign, blockAlign);
      samples[i] = (float) val / pow(2, (8 * blockAlign) - 1);
    }
    
    readFrequencies();
  }
  
  
  public void readFrequencies(){    
    
    amplitudes = new float[160 * 120];
    
    // Auslesen der Basis-Frequenz
    float baseValue = dft(1);
    
    // Skalieren der Amplituden-Werte
    for (int i = 2; i < 160 * 120 + 2; i++){
    
      // Der Farbwert wird als Prozentwert an der Basisfrequenz interpretiert.
      float val = dft(i);
      val /= baseValue;
      
      amplitudes[i - 2] = val;
    }
  }
  
  
  public float dft(int xi){
  
    PVector avg = new PVector(0, 0);
    int N = samples.length;
    
    // Summe bilden
    for (int n = 0; n < N; n++){
    
      // Berechnung der komplexen Zahl
      PVector samplePoint = new PVector(cos(-xi * n * TAU / N), sin(-xi * n * TAU / N));
      samplePoint.mult(samples[n]);
      
      avg.add(samplePoint);
    }
    
    return avg.mag();
  }
  
  
  /*
  void show(){
    
    float deltaX = (float) width / samples.length;
    float maxY = (float) height / 2;
    
    background(35);
    stroke(50);
    pushMatrix();
    translate(0, height / 2);
    
    line(0, 0, width, 0);
    
    stroke(235);
    for (int i = 0; i < floor((float) samples.length / zoom) - 1; i++){
      line(deltaX * i * zoom, -samples[i] * maxY, deltaX * (i + 1) * zoom, -samples[i + 1] * maxY);
    }
    popMatrix();
  }
  */
}


public int LEtoInt(byte[] bytes, int startByte, int blockLength){
  
  int result = 0;
  
  for (int i = blockLength - 1; i >= 0; i--){
    int val = bytes[startByte + i];
    if (i < blockLength - 1 && val < 0){
      val = 256 + val;
    }
    val *= pow(2, i * 8);
    
    result += val;
  }
  
  return result;
}


  public void settings() { size(160*7, 120*7); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "Empfaenger" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
